!(c) 2019, Jakub Mikula
!mikula_jakub@centrum.sk

FINISH
/clear
/prep7

L = 62.5
H = 60.0 
R1 = 6.0
R2 = 4.0 

k
k,,L
k,,L,H
k,,,H

l,1,2
l,2,3
l,3,4
l,4,1

k,,2*R1,2*R1 
k,,2*R1,H-2*R1 
k,,L-15,H/2-5 
k,,L-27.5,H/2+9

circle,5,R1 
circle,6,R1 
circle,7,R2 
circle,8,R2 

k,,,H/2+1.5
k,,L-37.5-1.5,H/2+1.5
k,,L-37.5,H/2 
k,,L-37.5-1.5,H/2-1.5
k,,,H/2-1.5

! expected area of crack growth
l,25,26
l,26,27
l,27,28
l,28,29
l,29,25

l,26,23
l,28,19

k,,L-15,H/2+9
l,18,30
l,30,21

! create areas from lines
al,1,2,3,4
al,21,22,23,24,25
al,22,23,27,14,28,29,20,19,26
al,19,20,17,18
al,15,16,13,14
al,5,6,7,8
al,9,10,11,12

APTN,ALL	!area partition
adele,7		!make holes
adele,6
adele,4
adele,5
adele,2

! finite element
ET,1,82
KEYOPT,1,3,2 !plane strain conditions

! isotropic elasticity
MP,EX,1,210000
MP,PRXY,1,0.3

LESIZE,27,1
LESIZE,14,1
LESIZE,28,1
LESIZE,29,1
LESIZE,20,1
LESIZE,19,1
LESIZE,26,1
LESIZE,22,1
LESIZE,23,1

LESIZE,1,5
LESIZE,2,5
LESIZE,3,5
LESIZE,31,5
LESIZE,30,5

AMESH,8
! The area with the crack will (re)mesh automatically

! boundary conditions
DK,14,,,,0,UX
DK,12,,,,0,UX
DK,12,,,,0,UY
FK,14,FY,100 !100 N force


! divide lines
LDIV,      22,  0.5
LDIV,      23,  0.5
LDIV,      14,  0.01

LDELE,25

! end of macro
